config/routes.rb
Privly::Application.routes.draw do
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  match '/posts/destroy_all' => 'posts#destroy_all', :method => :delete

  resources :token_authentications, :only => [:create, :new]
  match "token_authentications" => "token_authentications#show", :as => :show_token_authentications, :via => [:get, :post]
  match 'token_authentications' => 'token_authentications#destroy', :as => :destroy_token_authentications, :via => [:delete]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations' }

  devise_scope :user do 
    get "users/invitations" => "users/invitations#index", :as => :user_invitations
    post "users/invitations/send_invitation" => "users/invitations#send_invitation", :as => :user_send_invitations
    post "users/invitations/send_update" => "users/invitations#send_update", :as => :user_send_update
  end 

  root :to => "welcome#index"
  
  get "pages/account"
  
  get "pages/faq"
  get "pages/join"
  get "pages/roadmap"
  get "pages/people"
  get "pages/license"
  get "pages/privacy"
  get "pages/terms" => redirect("/pages/privacy")
  get "pages/help"
  get "pages/irc"
  get "pages/bug"
  get "pages/donate"
  get "pages/download"
  get "pages/about"
  get "pages/email"
  get "pages/kickstarter" => redirect("http://www.kickstarter.com/projects/229630898/protect-your-content-anywhere-on-the-web-privly")
  
  
  
  resources :posts
  match '/posts/posts_anonymous' => "posts#create_anonymous", :as => :create_anonymous_post, :via => [:post]
  resources :email_shares, :only => [:create, :destroy, :update]

  match '/' => 'welcome#index', :as => :welcome

end

app/views/shared/_nav.html.erb
<div id="topbanner">
    <div class="container">
        <h1 id="sitename"><a href="/">Priv.ly </a><span>Share Priv(ate).ly</span></h1>
        <div id="mainnav">
            <ul>
                
                <% if controller.controller_name == "sessions" %>
                    <% if user_signed_in? %>
                        <% if request.headers["auth_token"] %>
                            <li><%= link_to destroy_user_session_path, :method => :delete, :confirm => "The extension is still signed in, are you sure you want to logout of the website?" do %>
                                Logout
                                <span>auth</span>
                                <% end %>
                            </li>
                        <% else%>
                            <li><%= link_to destroy_user_session_path, :method => :delete do %>
                                Logout
                                <span>auth</span>
                                <% end %>
                            </li>
                        <% end %>
                    <% else %>
                    <li class="active"><%= link_to new_user_invitation_path do %>
                        Get Invited
                        <span>sign up</span>
                        <% end %>
                    </li>
                    <% end %>
                <% else %>
                    <% if user_signed_in? %>                    
                        <% if request.headers["auth_token"] %>
                            <li><%= link_to destroy_user_session_path, :method => :delete, :confirm => "The extension is still signed in, are you sure you want to logout of the website?" do %>
                                Logout
                                <span>auth</span>
                                <% end %>
                            </li>
                        <% else%>
                            <li><%= link_to destroy_user_session_path, :method => :delete do %>
                                Logout
                                <span>auth</span>
                                <% end %>
                            </li>
                        <% end %>
                    <% else %>
                    <li><%= link_to new_user_invitation_path do %>
                        Get Invited
                        <span>sign up</span>
                        <% end %>
                    </li>
                    <% end %>
                <% end %>
                
                <% if user_signed_in? %>
                    <li <% if controller.action_name == "account" %>class="active"<% end %>>
                        <%= link_to pages_account_path do %>
                            Account <span>info</span>
                        <% end %>
                    </li>
                <% else %>
                    <li <% if controller.controller_name == "pages" %>class="active"<% end %>>
                        <%= link_to pages_about_path do %>
                            About <span>more info</span>
                        <% end %>
                    </li>
                <% end %>
                
                <% if user_signed_in? %>
                    <% if controller.controller_name == "posts" %>
                        <li class="active"><a href="/posts">Posts <span>list</span></a></li>
                    <% else %>
                        <li><a href="/posts">Posts <span>list</span></a></li>
                    <% end %>
                <% end %>
                
                <% if extension_available? and not has_extension? %>
                    <li <% if controller.action_name == "pages" %>class="active"<% end %>>
                        <%= link_to pages_download_path do %>
                            Download Extension <span>for Browsers</span>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
</div>

app/views/shared/_sidebar.html.erb
<!--
These page items are explicitly included by hash values set in the controller
For example, when @sidebar[:post] evaluates to true, the post sidebar will be
included.
-->
<script type="text/javascript">
    $(function() {
        //creates the jquery UI based sidebar
        if($( "#sidebar_accordion" ) != null)
        {
            $( "#sidebar_accordion" ).accordion({autoHeight: false, 
                collapsible: true});
        }
        //pop up the download box if it is defined
        if($("#rightboxes") != null)
        {
            $("#downloadmessage").delay(1).fadeIn(2000);
            $("#rightboxes").delay(3000).slideDown("slow");
            updateURL();
        }
    });

    //Collects the parameters from the "Link Options" sidebar and
    //assigns the newFormattedLink element to the generated URL
    function updateURL()
    {
        var query_string = '?';
        var elem = document.getElementById('linkFormatterForm').elements;
        for(var i = 0; i < elem.length; i++)
        {
            if(elem[i].getAttribute("use_in_url") == "true")
            {
                var val = elem[i].value;
                if(! val)
                    continue;
                if(elem[i].type == "checkbox" && elem[i].checked != true)
                    continue;
                if(elem[i].type == "text")
                    val = val.replace(/[\s]/g,"+"); 
                query_string += elem[i].name + "=" + val + "&amp;";
            }
        } 
        document.getElementById('newFormattedLink').innerHTML = query_string;
    }
</script>

<% if @sidebar %>
<div id="sidebar">
    <div id="sidebar_accordion">
        
        <%# Show the context menus for a particular post %>
        <% if @sidebar[:post] %>
        <h2><a href="#">Post Info</a></h2>
        <div>
            <ul class="posts">
                <% if can? :destroy, @post %>
                    <% if @post.burn_after_date %>
                        <% if @post.burn_after_date > Time.now %>
                            <li>
                                <a>
                                    Destroyed in 
                                    <%= time_ago_in_words(
                                        @post.burn_after_date) %>
                                </a>
                            </li>
                        <% else %>
                            <li><a>This post is about to be destroyed</a></li>
                        <% end %>
                    <% else %>
                        <li><a>No Destroy Date Set</a></li>
                    <% end %>
                <% end %>
                <% if user_signed_in? %>
                    <% if current_user == @post.user %>
                        <li><a>You Own This</a></li>
                        <li>
                            <a class="date">
                                Posted 
                                <%= time_ago_in_words(@post.created_at) %> ago.
                            </a>
                        </li>
                    <% else %>
                        <li><a>An Anonymous User Owns This</a></li>
                    <% end %>
                <% else %>
                    <li>
                        <%= link_to "log in for ownership information",
                            new_user_session_url %>
                    </li>
                <% end %>
            </ul>
        </div>
        
        <%# Build link options for embedding elsewhere %>
        <h2><a href="#">Link Options</a></h2>
        <div>
            <ul class="posts">
                <%= form_tag nil, :id => "linkFormatterForm" do %>
                    <li>
                        Burn Message
                        <%= text_field_tag(:burnMessage, nil,
                            {:onkeyup=>"updateURL();", :use_in_url=>"true"}) %>
                    </li>
                    <li>
                        Passive Message
                        <%= text_field_tag(:passiveMessage, nil,
                            {:onkeyup=>"updateURL();", :use_in_url=>"true"}) %>
                    </li>
                    <li>
                        Force Passive?
                        <%= check_box_tag(:forcePassive, "true", false,
                            {:onclick=>"updateURL();", :use_in_url=>"true"}) %>
                    </li>
                    <li>
                        Exclude from Replacement?
                        <%= check_box_tag(:exclude, "true", false,
                            {:onclick=>"updateURL();", :use_in_url=>"true"}) %>
                    </li>
                    <% if @post.burn_after_date %>
                        <%= hidden_field_tag(:burntAfter, 
                            @post.burn_after_date.to_i, :use_in_url=>"true") %>
                    <% end %>
                    <% if @post.random_token %>
                        <%= hidden_field_tag(:random_token, 
                            @post.random_token, :use_in_url=>"true") %>
                    <% end %>
                <% end %>
            </ul>
        </div>
        <% end %><%# @sidebar[:post] %>
        
        <%# Create new content menus %>
        <% if @sidebar[:posts] %>
        <h2><a href="#">Write Posts</a></h2>
        <div>
            <ul class="posts">
                <% if user_signed_in? %>
                    <li><%= link_to 'New Private Post', new_post_path %></li>
                <% end %>
                <li><%= link_to 'New Public Post', 
                    new_post_path("post[public]"=>true) %></li>
            </ul>
        </div>
        <% end %><%# @sidebar[:posts] %>
        
        <%# Markdown format cheat sheet %>
        <% if @sidebar[:markdown] %>
        <h2>
            <a id="sidebar_markdown" href="#sidebar_markdown">
                Markdown Tips
            </a>
        </h2>
        <div>
            <ul class="posts">
                <li><em>*Emphasis*</em></li>
                <li><strong>**Strong**</strong></li>
                <li>[link text here](link.address.here "link title here")</li>
                <li>Line Break: a line ending in two spaces.</li>
                <li>1. An ordered list</li>
                <li>* An unordered list</li>
                <li>`<code>code</code>`</li>
                <li><h1># heading</h1></li>
                <li><h2>## subheading</h2></li>
                <li><h3>### sub-subheading</h3></li>
                <li><h3>### sub-subheading</h3></li>
                <li>
                    <%= link_to "More on Markdown", 
                        "http://en.wikipedia.org/wiki/Markdown",
                        {:target => "_blank"} %>
                </li>
            </ul>
        </div>
        <% end %><%# @sidebar[:markdown] %>
        
        <%# Contribute to the project menu %>
        <% if @sidebar[:contribute] %>
        <h2>
            <a id="sidebar_contribute" href="#sidebar_contribute">
                Contribute
            </a>
        </h2>
        <div>
            <ul class="posts">
                <li><%= link_to "Donate", pages_donate_path %></li>
                <li><%= link_to "Submit Bug Report", pages_bug_path %></li>
                <li><%= link_to "Join Up/Submit Code", pages_join_path %></li>
                <li><%= link_to "License", pages_license_path %></li>
            </ul>
        </div>
        <% end %><%# @sidebar[:contribute] %>
        
        <%# About the Site Menu %>
        <% if @sidebar[:about] %>
        <h2><a id="sidebar_about" href="#sidebar_about">About Us</a></h2>
        <div>
            <ul class="posts">
                <li><%= link_to "About", pages_about_path %></li>
                <li><%= link_to "Road Map", pages_roadmap_path %></li>
                <li><%= link_to "People", pages_people_path %></li>
                <li>
                    <%= link_to "Download Extension", pages_download_path %>
                </li>
            </ul>
        </div>
        <% end %><%# @sidebar[:about] %>
        
        <%# Show help information %>
        <% if @sidebar[:help] %>
        <h2><a id="sidebar_help" href="#sidebar_help">Help</a></h2>
        <div>
            <ul class="posts">
                <li><%= link_to "FAQ", pages_faq_path %></li>
                <li><%= link_to "Submit a Bug", pages_bug_path %></li>
                <li><%= link_to "Email", pages_email_path %></li>
                <li>
                    <%= link_to "Privacy/Terms of Service", 
                        pages_privacy_path %>
                </li>
            </ul>
        </div>
        <% end %><%# @sidebar[:help] %>
        
        <%# Show site news %>
        <% if @sidebar[:news] %>
        <h2><a id="sidebar_news" href="#sidebar_news">Site News</a></h2>
        <div>
            <ul class="menu">
                <li><%= link_to "Privly Twitter", 
                    "http://twitter.com/#!/Privly" %></li>
            </ul>
        </div>
        <% end %><%# @sidebar[:news] %>
    </div><!-- End of Accordion -->

    <%# Popup a message to download the extension %>
    <% if @sidebar[:download_extension] %>
        <div id="downloadmessage" class="rotate_sidebar" style="display:none;">
            <h2>View this content automatically</h2>
        </div>
        <% if @sidebar[:download_chrome_extension] %>
            <div id="rightboxes" style="display:none;">
                <div class="box1">
                    <p class="rotate">
                        <%= link_to("https://chrome.google.com/webstore/detail/pkokikcdapfpkkkjpdaamjanniaempol", :style => "color:#ffffff;") do %>
                          <span>Download the Extension</span>
                        <% end %>
                    </p>
                </div>
            </div>
        <% else %>
            <div id="rightboxes" style="display:none;">
                <div class="box1">
                    <p class="rotate">
                        <%= link_to("https://addons.mozilla.org/en-US/firefox/addon/privly/", :style => "color:#ffffff;") do %>
                          <span>Download the Extension</span>
                        <% end %>
                    </p>
                </div>
            </div>
        <% end %>
    <% end %><%# @sidebar[:download_extension] %>
</div>
<% end %>