config/routes.rb
Privly::Application.routes.draw do
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  match '/posts/destroy_all' => 'posts#destroy_all', :method => :delete

  resources :token_authentications, :only => [:create, :new]
  match "token_authentications" => "token_authentications#show", :as => :show_token_authentications, :via => [:get, :post]
  match 'token_authentications' => 'token_authentications#destroy', :as => :destroy_token_authentications, :via => [:delete]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations' }

  devise_scope :user do 
    get "users/invitations" => "users/invitations#index", :as => :user_invitations
    post "users/invitations/send_invitation" => "users/invitations#send_invitation", :as => :user_send_invitations
    post "users/invitations/send_update" => "users/invitations#send_update", :as => :user_send_update
  end 

  root :to => "welcome#index"
  
  get "pages/account"
  
  get "pages/faq"
  get "pages/join"
  get "pages/roadmap"
  get "pages/people"
  get "pages/license"
  get "pages/privacy"
  get "pages/terms" => redirect("/pages/privacy")
  get "pages/help"
  get "pages/irc"
  get "pages/bug"
  get "pages/donate"
  get "pages/download"
  get "pages/about"
  get "pages/email"
  get "pages/kickstarter" => redirect("http://www.kickstarter.com/projects/229630898/protect-your-content-anywhere-on-the-web-privly")
  
  
  
  resources :posts
  match '/posts/posts_anonymous' => "posts#create_anonymous", :as => :create_anonymous_post, :via => [:post]
  resources :email_shares, :only => [:create, :destroy, :update]

  match '/' => 'welcome#index', :as => :welcome

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @sidebar = {:news => false}
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% content_for(:title) do %>
    Welcome
<% end %>

<% content_for(:extracss) do %>
<style type="text/css">
.video_link {background-color: #242424;padding: 3px;}
.video_link a:link {color:#FFFFFF;}      /* unvisited link */
.video_link a:visited {color:#FFFFFF;}  /* visited link */
.video_link a:hover {color:#FFFFCC;}  /* mouse over link */
.video_link a:active {color:#0000FF;}  /* selected link */
</style>
<% end %>

<% content_for(:extrajs) do %>
    <script>
    
    function flashKickstarter()
    {
        $(".box1").animate({backgroundColor: "#FF0000"},1000);
        setTimeout(
          function(){
            $(".box1").css("background-color", "");
          },
          1400);
    }
    
    var current_video_id;
    
    function removeMessages(){
        var messageToRemove = ["#donate_text_2", "#roadmap_text_2", "#about_text_2"];
        var messageToAdd = ["#donate_text", "#roadmap_text", "#about_text"];
        
        for(var i = 0; i < messageToRemove.length; i++){
            $(messageToRemove[i]).slideUp("slow");
        }
        for(var i = 0; i < messageToAdd.length; i++){
            $(messageToAdd[i]).slideDown("slow");
        }
        
    }
    
    function stopVideo(){
        $("#video_back").slideUp();
        var number = current_video_id.match(/\d/g);
        var froogaloop = $f($("#player_" + number)[0]);
        froogaloop.addEvent("stop");
        $(current_video_id).toggle();
        removeMessages();
    }
    
    function viewVideo(video_id){
        $("#video_back").slideDown();
        current_video_id = video_id;
        $(video_id).toggle();
    }
    
    $(document).ready(function() {
        
        $("#page").css("border-right","0px"); 
        $("#mainimg").hover(function(){jQuery("#kickstarter_image").fadeOut(200)}, function(){jQuery("#kickstarter_image").fadeIn(200)});
    
        // when a vimeo video becomes ready, it calls ready.
        // Ready registers the event listeners for play and
        // finish. When a video finishes, the video area 
        // returns to the video selection page
        // events on it
        function ready(player_id) {
            //console.log('ready!');
            var froogaloop = $f(player_id);

            function onPlay() {
                    froogaloop.addEvent('play', function(data) {
                        //console.log(data);
                    });
            }

            function onFinish() {
                    froogaloop.addEvent('finish', function(data) {
                        if(data.indexOf(1) >= 0)
                            flashKickstarter();
                        stopVideo();
                        $("#video_back").slideUp();
                    });
            }

            onPlay();
            onFinish();
        }
    
        // Listen to the ready event
        var player = $('#player_1')[0];
        $f(player).addEvent('ready', ready);
        
        var player = $('#player_2')[0];
        $f(player).addEvent('ready', ready);
        
        var player = $('#player_3')[0];
        $f(player).addEvent('ready', ready);
        
        var player = $('#player_4')[0];
        $f(player).addEvent('ready', ready);
        
        function addEvent(element, eventName, callback) {
            if (element.addEventListener) {
                element.addEventListener(eventName, callback, false);
            }
            else {
                element.attachEvent(eventName, callback, false);
            }
        }
    });
    </script>
<% end %>

<% content_for :top_column do %>
<div id="homeheader">
    <div id="mainimg">
        <div style="position:relative;">
            <div id="video_controls" style="position:absolute;top:50px;left:160px;width:370px;">
                <p style="font-size: 23px;">
                    <span class="video_link"><%= link_to_function "1. Watch Kickstarter Pitch",
                        "viewVideo('#video_1');$('#donate_text').slideUp('slow');$('#donate_text_2').slideDown('slow');" %>
                    </span>
                    <br /><br />
                    <span class="video_link"><%= link_to_function "2. Watch 'How to Use Privly'",
                        "viewVideo('#video_2');$('#about_text').slideToggle('slow');$('#about_text_2').slideToggle('slow');" %>
                    </span>
                    <br /><br />
                    <span class="video_link"><%= link_to_function "3. Watch Roadmap Tour", 
                        "viewVideo('#video_3');$('#roadmap_text').slideToggle('slow');$('#roadmap_text_2').slideToggle('slow');" %>
                    </span><br /><br />
                    <span class="video_link"><%= link_to_function "4. Watch Encryption Tour", 
                        "viewVideo('#video_4');" %>
                    </span><br /><br />
                </p>
            </div>
            
            <div id="kickstarter_image" style="position:absolute;left:125px">
                <%= image_tag "kickstarter_new.jpg", :height => "330px" %>
            </div>
            
            <noscript>
                <p>You do not have scripts enabled, which means you are either running old technology, or are our kind of person. If you are the latter, we hope you will consider <%= link_to "helping out", pages_join_path %>.</p>
            </noscript>
            
            <div id="video_1" style="display:none;background:none;position:absolute;">
                <iframe id="player_1" src="https://player.vimeo.com/video/38477050?title=0&amp;byline=0&amp;portrait=0&amp;api=1&amp;player_id=player_1" width="700" height="330" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            </div>
            
            <div id="video_2" style="display:none;background:none;position:absolute;">
                <iframe id="player_2" src="https://player.vimeo.com/video/38477052?title=0&amp;byline=0&amp;portrait=0&amp;api=1&amp;player_id=player_2" width="700" height="330" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            </div>
            
            <div id="video_3" style="display:none;background:none;position:absolute;">
                <iframe id="player_3" src="https://player.vimeo.com/video/38477051?title=0&amp;byline=0&amp;portrait=0&amp;api=1&amp;player_id=player_3" width="700" height="330" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            </div>
            
            <div id="video_4" style="display:none;background:none;position:absolute;">
                <iframe id="player_4" src="https://player.vimeo.com/video/39095681?title=0&amp;byline=0&amp;portrait=0&amp;api=1&amp;player_id=player_4" width="700" height="330" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            </div>
            
            <div id="video_back" style="display:none;background:none;position:absolute;top:10px;right:0px;width:370px;text-align: right;">
                <p>
                    <span class="video_link"><%= link_to_function "Back to Video List", "stopVideo();" %></span>
                </p>
            </div>
            
        </div>
    </div>
    <div id="rightboxes">
        <div class="box1">
            <p class="rotate">
                <%= link_to(pages_kickstarter_path) do %>
                  <span id="go_to_kickstarter">Donate to our Kickstarter</span>
                <% end %>
            </p>
        </div>
        <div class="box2">
            <p class="rotate">
                <% if extension_available? and not has_extension? %>
                    <%= link_to(pages_download_path(:anchor => "extension")) do %>
                      <span>Download Extension</span>
                    <% end %>
                <% else %>
                    <%= link_to pages_about_path do %>
                      <span>Learn More About Privly</span>
                    <% end %>
                <% end %>
            </p>
        </div>
        <div class="box3" id="invite_visual">
            <p class="rotate">
                <a href="#" onclick="$('#invite_visual').slideUp('slow');$('#invite_form').slideDown('slow');">
                  <span>Sign-up for Invitation</span>
                </a>
            </p>
        </div>
        <div class="box3" id="invite_form" style="display:none;background:none">
            
            <%= form_for "user", :as => "user", :url => invitation_path("user"), :html => {:method => :post} do |f| %>
              <h2>Invitation
                  <%= f.label :email %><br />
                  <%= f.text_field :email %><br />
                  <%= f.submit "Sign up for an invitation" %>
              </h2>
            <% end %>
        </div>
    </div>
    <div class="clear"></div>
</div>
<% end %>

<% content_for :top_main_content_column do %>
    <div id="threecol">
        <div class="col1">
            <div id="about_text">
                <h2><%= link_to "About", pages_about_path %></h2>
                <p>Privly is a proof-of-concept for a new standard of private sharing. It is the only way to maintain control of your data on the social web. <%= link_to "Learn More.", pages_about_path %></p>
            </div>
            
            <div id="about_text_2" style="display:none;background:none;">
                <h2><%= link_to "Try it Out!", pages_download_path %></h2>
                <p>
                    We have demonstration extensions for Firefox and Chrome. <%= link_to "Install the extension", pages_download_path %> to see how easy privacy can be.
                </p>
            </div>
        </div>
        
        <div class="col2">
            <div id="roadmap_text">
                <h2><%= link_to "Roadmap", pages_roadmap_path %></h2>
                <p>Privly is the core of a novel sharing and privacy feature set. For more information, read our <%= link_to "Roadmap", pages_roadmap_path %> or <%= link_to "About Page.", pages_about_path %></p>
            </div>
            <div id="roadmap_text_2" style="display:none;background:none;">
                <h2><%= link_to "Read the Roadmap!", pages_roadmap_path %></h2>
                <p>After you are done with the <%= link_to "Roadmap", pages_roadmap_path %> video, we have a special treat for you! The <span style="font-style:italic;">actual</span> <%= link_to "Roadmap", pages_roadmap_path %>.</p>
            </div>
        </div>

        <div class="col3">
            <div id="donate_text">
                <h2><%= link_to "Donate", pages_donate_path %></h2>
                <p>The best place to donate is at our <%= link_to "Kickstarter campaign.", pages_kickstarter_path %> We also accept <%= link_to "donations", pages_donate_path %> by Bitcoin, PayPal, and anything else you want us to set up.</p>
            </div>
            <div id="donate_text_2" style="display:none;background:none;">
                <h2><%= link_to "Kickstart Us!", pages_kickstarter_path %></h2>
                <p>
                    <%= link_to "Kickstarter", pages_kickstarter_path %> is an all-or-nothing crowd funding platform. If we meet our goal, we will continue development. You can also <%= link_to "donate", pages_donate_path %> to us directly.
                </p>
            </div>
        </div>
        
        <div class="clear"></div>
    </div>
<% end %>