config/routes.rb
Privly::Application.routes.draw do
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  match '/posts/destroy_all' => 'posts#destroy_all', :method => :delete

  resources :token_authentications, :only => [:create, :new]
  match "token_authentications" => "token_authentications#show", :as => :show_token_authentications, :via => [:get, :post]
  match 'token_authentications' => 'token_authentications#destroy', :as => :destroy_token_authentications, :via => [:delete]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations' }

  devise_scope :user do 
    get "users/invitations" => "users/invitations#index", :as => :user_invitations
    post "users/invitations/send_invitation" => "users/invitations#send_invitation", :as => :user_send_invitations
    post "users/invitations/send_update" => "users/invitations#send_update", :as => :user_send_update
  end 

  root :to => "welcome#index"
  
  get "pages/account"
  
  get "pages/faq"
  get "pages/join"
  get "pages/roadmap"
  get "pages/people"
  get "pages/license"
  get "pages/privacy"
  get "pages/terms" => redirect("/pages/privacy")
  get "pages/help"
  get "pages/irc"
  get "pages/bug"
  get "pages/donate"
  get "pages/download"
  get "pages/about"
  get "pages/email"
  get "pages/kickstarter" => redirect("http://www.kickstarter.com/projects/229630898/protect-your-content-anywhere-on-the-web-privly")
  
  
  
  resources :posts
  match '/posts/posts_anonymous' => "posts#create_anonymous", :as => :create_anonymous_post, :via => [:post]
  resources :email_shares, :only => [:create, :destroy, :update]

  match '/' => 'welcome#index', :as => :welcome

end

app/views/pages/account.html.erb
<% content_for(:title) do %>
    Account
<% end %>

<h2 class="subhead"><span>Account</span></h2>

<p class="postmeta"><%= link_to 'Destroy All Posts', posts_destroy_all_path, :confirm => 'Are you sure? This will destroy everything you know and love in this site.', :method => :delete %></p>

<p class="postmeta"><%= link_to 'Export All Posts', {:controller => "posts", :action => "index", :format => :csv}, :confirm => 'Are you sure? This will export all of your posts in .csv format.'%></p>

<p class="postmeta">To change your password, <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %> and check login options to manage your password.</p>

<p class="postmeta">The email associated with this account is: <%= current_user.email %></p>

app/views/pages/bug.html.erb
<% content_for(:title) do %>
    Bug
<% end %>

<h2 class="subhead"><span>Bugs</span></h2>

<div class="post">
    <div class="posthead">
        <h3>Please tell us what we are doing wrong!</h3>
    </div>
    <p>If it is an issue with the content server (Priv.ly), make sure you include the URL with the error and a description of the problem.</p>
    <p>If it is an issue with a particular website, make sure you include:</p>
    <ul>
        <li>The version of the extension you were using (if any)</li>
        <li>A link to the host page with a public Priv.ly link</li>
        <li>Your browser name and version</li>
        <li>Your operating system</li>
        <li>A description of the behavior</li>
    </ul>
    <p>Once you gather the relevant information, submit an issue to the relevant system below. Thanks!</p>
    <ul>
        <li><%= link_to "Firefox Extension Issues", "https://github.com/smcgregor/privly-firefox/issues" %></li>
        <li><%= link_to "Chrome Extension Issues", "https://github.com/smcgregor/privly-chrome/issues" %></li>
        <li><%= link_to "Content Server Issues (this site)", "https://github.com/smcgregor/privly-web/issues" %></li>
    </ul>
    
</div>

app/views/pages/download.html.erb
<% content_for(:title) do %>
    Download Extensions
<% end %>

<% content_for(:extrajs) do %>
<script type="text/javascript">
    $(document).ready(function() {
      $("#chrome_link").mouseenter(function(){$("#chrome_message").slideDown("slow")});
      $("#chrome_link").mouseleave(function(){$("#chrome_message").slideUp("slow")});
      
      $("#firefox_link").mouseenter(function(){$("#firefox_message").slideDown("slow")});
      $("#firefox_link").mouseleave(function(){$("#firefox_message").slideUp("slow")});
    });
</script>
<% end %>

<h2 class="subhead"><span>Download</span></h2>

<p>The extensions are pre-alpha and are under active development. Check back later if you do not like change and filing <%= link_to "bug reports", pages_bug_path %>. We will announce developments on Privly's <%= link_to "Twitter", "http://twitter.com/#!/Privly" %> account.</p>

<br />

<div style="color: #FF0000;">
    <p>Please note that the extension does <span style="font-weight:bold;">not</span> currently offer:</p>
    <ul>
        <li>Encryption (content is stored in the clear)</li>
        <li>Protection from governments</li>
        <li>Protection from our hosting provider</li>
        <li>Protection from the domain name system</li>
        <li>Or security of any kind</li>
    </ul>
    <p>We made the extension available so you can test it out with your favorite site, but until we tell you otherwise, post with the expectation that it is public.</p>
</div>


<br />

<div style="margin-bottom: 225px;">
    <div id="firefox_link" style="float: left; width: 50%;">
        <%= link_to("https://addons.mozilla.org/en-US/firefox/addon/privly/") do %>
            <div style="height: 150px">
                <%= image_tag "firefox_logo_150.png", :alt => "Firefox Logo", :style=>"display: block;margin-left: auto;margin-right: auto;" %>
            </div>
            <div name="extension" style="text-align: center">
                <h1 id="firefox">Firefox Extension</h1>
                <div id="firefox_message" style="display:none;background:none">
                    <p>The Firefox extension supports viewing Privly links, and uploading new content directly to the Privly servers.</p>
                </div>
            </div>
        <% end %>
    </div>

    <div id="chrome_link" style="float: left; width: 50%;">
    <%= link_to("https://chrome.google.com/webstore/detail/pkokikcdapfpkkkjpdaamjanniaempol") do %>
        <div style="height: 150px">
            <%= image_tag "chrome-logo_150X.png", :alt => "Chrome Logo", :style=>"display: block;margin-left: auto;margin-right: auto;" %>
        </div>
        <div name="extension" style="text-align: center">
            <h1 id="chrome">Chrome Extension</h1>
            <div id="chrome_message" style="display:none;background:none">
                <p>The Chrome extension allows you to view links, but extension-side link submission is still under development.</p>
            </div>
        </div>
    <% end %>
    </div>
</div>

<br />
<br />

<p style="text-align: center;">
<%= link_to_function "Where is my browser?", "$('#browser_not_Listed').slideToggle('slow')" %>
</p>
<div id="browser_not_Listed" style="display:none;background:none">
    <p>We need to bring Privly to other browsers and platforms, so if you don't see your endpoint here, please consider <%= link_to "joining", pages_join_path %> the team.</p>
</div>


<br />

<h1>Test Your Extension on These Pages</h1>
<p>The following pages are pre-seeded with Privly content so you can test the extension out: <%= link_to "Facebook", "https://www.facebook.com/profile.php?id=100002254562518&sk=wall" %> and <%= link_to "Twitter", "https://twitter.com/#!/PrivlyTest" %>. You can also post the public links below to any website to see how it handles. Let us know if you have any <%= link_to "problems", pages_bug_path %>. It should work in any basic HTML form. <%= link_to "Kickstarter", "http://www.kickstarter.com/projects/229630898/protect-your-content-anywhere-on-the-web-privly" %> backers can also create new content.</p>

<br />
<br />
<h1>Post these Links Anywhere</h1>
<br/>
<p>
    <ol>
        <li>I just tried out Privly!... <br/><br/>https://priv.ly/posts/74</li>
        <br/><br/>
        <li>Give Me Liberty or Give me Death... <br/><br/>https://priv.ly/posts/3</li>
    </ol>
</p>

app/views/pages/email.html.erb
<% content_for(:title) do %>
    Email List
<% end %>

<h2 class="subhead"><span>Email</span></h2>

<p>
    You can join our email list to track the public development of the site and extensions. You can also ask for help, but make sure you check the <%= link_to "FAQ", pages_faq_path %> first.
    <br />
    <br />
    <a href="http://groups.google.com/group/privly">Visit the email group</a>
</p>

app/views/pages/faq.html.erb
<% content_for(:title) do %>
    Frequently Asked Questions
<% end %>

<h2 class="subhead"><span>Frequently Asked Questions</span></h2>

<div class="post">
    <div class="posthead">
        <label>
        <h2>Why is this an open source project?</h2>
        <p>We see Privly as a protocol, not a content network. We will build out the standard functionality and libraries so you can bring the system to whatever platform you work with. We also want to develop the concept into an information security application, and you should distrust any "secure" platform that will not let you audit and improve their source code.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <label>
        <h2>Why Should I Write Code for Privly?</h2>
        <p>Privly is and will always be open source. Your code will attempt to reshape the way the "link economy" functions, and just like the web, no one owns it. Code for Privly if you are passionate about taking back your content, using the web in new ways, or need an easier way to share information securely.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <label>
        <h2>Why should I donate to Privly?</h2>
        <p>Privly must be a community supported project, and without your help, we will not make it. If someone does not solve the privacy and content ownership problem, then we are left with the status quo, which is unacceptable.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <label>
        <h2>How are you going to make money off of this?</h2>
        <p>(this one is a little technical) Privly's server load is potentially as high as Twitter's, and they have millions of dollars in funding. Since we are taking our idea to the people, rather than the venture capitalists, we will distribute the load to our users by allowing them to run their own Privly content servers. Content hosted by third party servers will not be included on a white list for automatic page inclusion unless the end user adds them to their personal white list. Third party commercial interests can gain various levels of automatic-inclusion permissions by paying for an audit of their security and privacy. This is similar to the way Mozilla generates revenue from their preferred search providers, but we will not allow tracking. We are also looking into ways of distributing encrypted content with peer-to-peer technology in a way that will not sacrifice browsing anonymity. Privly will also offer paid premium services where the services carry a financial burden for Privly. Basically, Privly will make money where it has expenses. We will work off of donations as long as possible.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <label>
        <h2>When Will Privly Reach an Open Beta?</h2>
        <p>Privly will reach an open Beta when it has a stable extension for 80 percent of the market, and server capacity to meet projected demand. We will not get there without help, so please consider <%= link_to "joining the team.", pages_join_path %> We also want to know if you would use the system, so please sign up for an <%= link_to "invitation", new_user_invitation_path %> if you want to keep us coding.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <label>
        <h2>Can I Serve Content Through a Privly Link?</h2>
        <p>For the time being, content must be served from Privly servers. Before we open up an API for other content servers, we need to secure the extensions and provide a mechanism for whitelisting content hosts. Privly extensions need to prevent phishing, scripting attacks, and the tracking of our readers. You can help us get to an API by <%= link_to "joining the team.", pages_join_path %></p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <label>
        <h2>Are You Competing with <%= link_to "Diaspora", "http://joindiaspora.org" %>?</h2>
        <p>Privly does <strong>not</strong> want to be another social network. Diaspora is a solid foundation for secure sharing, but you can't share Diaspora content securely everywhere. We can change that by injecting link content into secure page elements. We want to reduce Diaspora, and all social networks to their core offering: a social graph. They do not need your content, they need a reference to your content.</p>
        <br/>
        <p>Privly's goal is to set a new standard, whereby only the content creators and their designees have access to the cleartext. Privly, Diaspora, Facebook, Google, Twitter, <i>et al.</i> never need access.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <label>
        <h2>Will this destroy my web site's layout?</h2>
        <p>In all test cases to date, Privly content has not affected page layout adversely. We can use sites in ways other than they were intended, like embedding a chat room in a Twitter feed, or putting a Wiki in an article's comment, but it does not change the layout or design of the host site. We hope the system will gain wider acceptance, and sites will be able to specify how injected content should be displayed. The core functionality of the Privly system can be used without a browser extension, if the host site runs our script.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <label>
        <h2>Ask a Question by <%= link_to "email list", pages_email_path %> or <%= link_to "contact us.", pages_people_path %></h2>
        <p></p>
    </div>
</div>

app/views/pages/help.html.erb
<% content_for(:title) do %>
    Help
<% end %>

<h2 class="subhead"><span>Help</span></h2>

app/views/pages/join.html.erb
<% content_for(:title) do %>
    Join
<% end %>

<h2 class="subhead"><span>Join</span></h2>

<div class="post">
    <div class="posthead">
        <h3>Like the project?</h3>
        <p>Then Join Up! Introduce yourself to the <%= link_to "email list", "http://groups.google.com/group/privly" %>, or contact Sean by email: privlycontact [at] seanbmcgregor.com. We are just beginning the open development process, so there will not be a better time to contribute. Also great ways to move the project forward:</p>
        <ul>
            <li>Fork a Repository
                <ul>
                    <li><%= link_to "Web Application", "https://github.com/smcgregor/privly-web" %> (the content/key server)</li>
                    <li><%= link_to "Firefox Extension", "https://github.com/smcgregor/privly-firefox" %></li>
                    <li><%= link_to "Chrome Extension", "https://github.com/smcgregor/privly-chrome" %></li>
                    <li><%= link_to "Opera Extension", "https://github.com/smcgregor/privly-opera" %></li>
                    <li><%= link_to "Internet Explorer Extension", "https://github.com/smcgregor/privly-ie" %></li>
                    <li><%= link_to "Safari Extension", "https://github.com/smcgregor/privly-safari" %></li>
                    <li><%= link_to "Test Cases", "https://github.com/smcgregor/privly-test" %></li>
                </ul>
            </li>
            <li>Bring Privly to a new Platform
                <ul>
                    <li>(your extension here)</li>
                </ul>
            </li>
            <li>Do one of the things listed <%= link_to "here", pages_roadmap_path %></li>
            <li>Write documentation</li>
            <li>Write tests</li>
            <li><%= link_to "Submit bugs", pages_bug_path %></li>
            <li>Redesign the site (as you can tell, we don't have anyone with a sense of style)</li>
            <li>Integrate other content hosts with the priv.ly link</li>
        </ul>
        <p>If you don't have the time but you have the money, we accept <%= link_to "donations", pages_donate_path %>.</p>
    </div>
</div>

app/views/pages/kickstarter.html.erb
<% content_for(:title) do %>
    Kickstarter
<% end %>

<h2 class="subhead"><span>Kickstarter Campaign</span></h2>

<div class="post">
    <div class="posthead">
        <h3>Launching Soon</h3>
        <p>We are a button press away from launching our Kickstarter. Contact <%= link_to "Sean McGregor", pages_people_path %> If you want to preview the Kickstarter.</p>
    </div>
</div>

app/views/pages/license.html.erb
<% content_for(:title) do %>
    License
<% end %>

<h2 class="subhead"><span>License</span></h2>

<p>We are licensing all extensions and server code under the MIT license, see the <a href="/license.txt">License File.</a></p>

<br />

<%= image_tag("OSI-Approved-License-100x137.png", :style=>"display: block;   margin-left: auto;   margin-right: auto;") %>

app/views/pages/people.html.erb
<% content_for(:title) do %>
    People
<% end %>

<h2 class="subhead"><span>People</span></h2>

<div class="post">
    <div class="posthead">
        <h3><%= link_to "Sean McGregor,", "http://www.linkedin.com/in/seanbmcgregor", :target => "_blank" %> Lead Developer</h3>
        <p>Sean is a <%= link_to "Machine Learning", "http://en.wikipedia.org/wiki/Machine_learning" %> PhD student at Oregon State University. He began developing the Privly concept in response to platforms asserting ownership over their community's content. You can contact him by email, privlycontact [at] seanbmcgregor.com, <%= link_to "Twitter", "https://twitter.com/#!/seanmcgregor" %> or by <%= link_to_function "phone", "$('#phone_object').slideToggle('slow');"  %>. Outside web development and research, Sean enjoys rock climbing, Cuban Salsa, and Judo.</p>
    </div>
    <div id="phone_object" style="display:none;background:none">
        <p>Google will call the number you enter, then connect you with Sean.</p>
        <object  type="application/x-shockwave-flash" data="https://clients4.google.com/voice/embed/webCallButton" width="230" height="85"><param name="movie" value="https://clients4.google.com/voice/embed/webCallButton" /><param name="wmode" value="transparent" /><param name="FlashVars" value="id=836f2d2661d2ac4d60dc333adab5f77d6b53eb97&style=0" />Requires Flash player.</object>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <h3><%= link_to "Balaji Athreya, ", "http://www.linkedin.com/in/balajiathreya", :target => "_blank" %>Client Side Developer</h3>
        <p>Balaji Athreya is a graduate student in Computer Science at Oregon State University studying Software Engineering and Usability. His Privly work is focussed on the Firefox Extension. He likes filter coffee, programming and Ilayaraja in no specific order.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <h3><%= link_to_function "Jesse Hostetler, ", "alert('HOSTETLER does NOT like public websites. Contact us if you find something good to link to...');" %>Client Side Developer</h3>
        <p>Jesse is a <%= link_to "Machine Learning", "http://en.wikipedia.org/wiki/Machine_learning" %> PhD student at Oregon State University. His Privly work is focused on encryption libraries for the extensions.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <h3><%= link_to "Jennifer Davidson, ", "http://health.oregonstate.edu/igert/people/students", :target => "_blank" %>Community Manager</h3>
        <p>Jennifer is a Computer Science PhD student at Oregon State University. Her research focuses on older adults in the design and development of open source software. In general, she is interested in how open source communities operate. Aside from research, she enjoys doing outreach with women in technology. She is a <%= link_to "Systers", "http://anitaborg.org/initiatives/systers/" %> member and helps with <%= link_to "ChickTech", "http://chicktech.org" %>. In her luxurious free time, she’s a live music goer, beer enthusiast and road tripper. You can find her on <%= link_to "twitter", "https://twitter.com/#!/jewifer" %>. <%= link_to "LinkedIn", "http://www.linkedin.com/pub/jennifer-davidson/15/b8/181" %>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <h3><%= link_to "Jesse Pollak,", "http://jessepollak.me" %> Server and Client Side Developer</h3>
        <p>Jesse is a computer science major at <%= link_to "Pomona College", "http://www.pomona.edu/" %>. He loves playing soccer, skiing, and almond croissants. Since joining in the first week of Privly's <%= link_to "Kickstarter", "http://www.kickstarter.com/projects/229630898/protect-your-content-anywhere-on-the-web-privly" %>, he has worked on making Privly data more portable, stylish, and is currently working on a Safari version of the extension.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <h3><%= link_to "Swetal Patel, ", "http://www.linkedin.com/in/teamswet" %>Jargon Translator/PR</h3>
        <p>Swet is a San Diego resident born and raised. Since getting his B.A. in 2008, he has been working in e-commerce marketing. In addition to being Privly's first donor, Swet is working to make the Privly concept accessible to the masses. He enjoys gadgets, music and is a film and TV buff.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <h3><%= link_to "Tyler Dugoni, ", "http://thinkshootdesign.com/" %>Graphic Design</h3>
        <p>Tyler has been a Web Developer and Graphic Designer since age 12. He uses is skills for freelance work in web development, and graphic design. Since joining Privly during the <%= link_to "Kickstarter", "http://www.kickstarter.com/projects/229630898/protect-your-content-anywhere-on-the-web-privly" %> campaign, Tyler has generated new graphics for the campaign, site, and extension. Tyler is always looking for ways to sharpen his skills, and is always designing! Tyler enjoys live concerts and anything that has to do with computers.</p>
    </div>
</div>

<div class="post">
    <div class="posthead">
        <h3><%= link_to "Your Name Here,", pages_join_path %> Your Role</h3>
        <p>We have set an <%= link_to "ambitious agenda", pages_roadmap_path %>, but we won't get anywhere without help. Your Name Here enjoys rocketry, SCIENCE!, and generally being awesome at life.</p>
    </div>
</div>

<h2>Code Contributors</h2>

<div class="post">
    <div class="posthead">
        <p>Even if you don't want to <%= link_to "join", pages_join_path %> feel free to submit patches or one-off features.</p>
        <br />
        <p>Privly has benefited from the existence of numerous open source projects. We should note that the template for the site was originally designed by <span class="credit"><a href="http://cssheaven.org" title="free and open source css template">CSS Heaven</a> and Released under the GPL License.</span> All other components of the site and extensions are MIT licensed.</p>
    </div>
</div>