config/routes.rb
Privly::Application.routes.draw do
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  match '/posts/destroy_all' => 'posts#destroy_all', :method => :delete

  resources :token_authentications, :only => [:create, :new]
  match "token_authentications" => "token_authentications#show", :as => :show_token_authentications, :via => [:get, :post]
  match 'token_authentications' => 'token_authentications#destroy', :as => :destroy_token_authentications, :via => [:delete]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations' }

  devise_scope :user do 
    get "users/invitations" => "users/invitations#index", :as => :user_invitations
    post "users/invitations/send_invitation" => "users/invitations#send_invitation", :as => :user_send_invitations
    post "users/invitations/send_update" => "users/invitations#send_update", :as => :user_send_update
  end 

  root :to => "welcome#index"
  
  get "pages/account"
  
  get "pages/faq"
  get "pages/join"
  get "pages/roadmap"
  get "pages/people"
  get "pages/license"
  get "pages/privacy"
  get "pages/terms" => redirect("/pages/privacy")
  get "pages/help"
  get "pages/irc"
  get "pages/bug"
  get "pages/donate"
  get "pages/download"
  get "pages/about"
  get "pages/email"
  get "pages/kickstarter" => redirect("http://www.kickstarter.com/projects/229630898/protect-your-content-anywhere-on-the-web-privly")
  
  
  
  resources :posts
  match '/posts/posts_anonymous' => "posts#create_anonymous", :as => :create_anonymous_post, :via => [:post]
  resources :email_shares, :only => [:create, :destroy, :update]

  match '/' => 'welcome#index', :as => :welcome

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= Rails.application.class.parent %> &middot; <%= yield :title %></title>
  
  <%= stylesheet_link_tag    :application %>
  <%= javascript_include_tag :application %>
  
  <%= yield :extrahead %>
  <%= yield :extracss %>
  <%= yield :extrajs %>

  <%= csrf_meta_tags %>
  
</head>
<body privly-exclude="true">

<!--TOP BANNER AND NAVIGATION -->
<%= render "shared/nav" %>

<div id="pagewrap">
    <div id="wrap" style="min-height:400px;">
        <% if notice %>
        <div class="flash notice">
            <p><%= notice %></p>
        </div>
        <% end %>
        <% if alert %>
        <div class="flash alert">
            <p><%= alert %></p>
        </div>
        <% end %>
        <%= yield :top_column %>
        <div id="maincontent">
                
            <!-- OPTIONAL MAIN CONTENT AREA, used mostly on welcome page-->
            <%= yield :top_main_content_column %>
                
            <div class="clear bordered"></div>
                
            <!--MAIN CONTENT-->
            <div id="page">
                <%= yield %>
            </div>
            
            <%= render "shared/sidebar" %>
            
            <div class="clear"></div>
        </div>
    </div>
</div>


<div id="bottom">
    <!--Bottom Row -->
    <div id="btmcontent">
        <div class="col1">
            <h2>Contribute</h2>
            <p>We are an <a href="/pages/license">open source</a> project so there are many ways to contribute.</p>
            <ul>
                <li><%= link_to "Donate", pages_donate_path %></li>
                <li><%= link_to "Submit Bug Report", pages_bug_path %></li>
                <li><%= link_to "Join Up/Submit Code", pages_join_path %></li>
                <li><%= link_to "License", pages_license_path %></li>
            </ul>
        </div>
        <div class="col2">
            <h2>Help</h2>
            <p>We are still in the early stages of development, so expect a few bugs. </p>
            <ul>
                <li><%= link_to "FAQ", pages_faq_path %></li>
                <li><%= link_to "Submit a Bug", pages_bug_path %></li>
                <li><%= link_to "Email", pages_email_path %></li>
                <li><%= link_to "Privacy/Terms of Service", pages_privacy_path %></li>
            </ul>
        </div>
        <div class="col3">
            <h2>About Us</h2>
            <p>The Privly concept is open source community project for taking control of your personal information.</p>
            <ul>
                <li><%= link_to "About", pages_about_path %></li>
                <li><%= link_to "Road Map", pages_roadmap_path %></li>
                <li><%= link_to "People", pages_people_path %></li>
                <li><%= link_to "Download Extension", pages_download_path %></li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
    
    <!--FOOTER 
    <div id="footer">
        <p>Priv.ly</p>
        <span class="credit"><a href="http://cssheaven.org" title="free and open source css template">CSS Template</a> by CSS Heaven Released under GPL License</span>
    </div>-->
</div>
</body>
</html>